apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-app-deployment
  labels:
    app: patient-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-devops-app
  template:
    metadata:
      labels:
        app: patient-devops-app
    spec:
      containers:
        - name: patient-devops-app
          image: abhishek/patient-devops-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"