apiVersion: v1
kind: Service
metadata:
  name: patient-app-service
spec:
  selector:
    app: patient-devops-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
